### ISSUE TITLE
How to disable some build steps like TravisCI, Releasing to Gihub etc.

### ISSUE THREAD

**Issue by skorunka** [tinesoft/generator-ngx-library#130]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] feature request
```

### OS and Version?
Windows 10

### Generator Version
5.1.0

### Tools Version
Output from: `2.0.0`, 
Output from: `8.7.0`, 
Output from: `5.5.1` npm

### Targeted Angular version
5.x

### Desired functionality.
Be able to easily disable some steps, like TravisCI, Releasing to Gihub etc.

For now, the only solution is to edit `gulpfile.js`?

**Comment by tinesoft** [comment]
Hi @skorunka 

Right now, you can only specify _additional tasks_(via `config/gulp-tasks`) without changing the `gulpfile.js`.
But to change the current workflow, i'm afraid  you will have to edit the `gulpfile.js`.

I leave the ticket open for now. I'll think of a way to customize that too, in upcoming releases.

Cheers!

**Comment by skorunka** [comment]
Ok, having it configurable would be a nice feature. Thanks.

**Comment by tinesoft** [comment]
Just released [v5.3.0](https://github.com/tinesoft/generator-ngx-library/releases/tag/v5.3.0) with some options to skip Travis, Covealls, Github Releasing

Enjoy!
