### ISSUE TITLE
include (i.e. scss) files in lib

### ISSUE THREAD

**Issue by matthiasscudlik** [tinesoft/generator-ngx-library#138]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request / question
```
###
I want to include some scss files in my library, so that consumers can easily import and overwrite some of the default values (i.e. colors, ...).
For this i have created a folder scss in lib and created a _variables.scss file.

If i now build the library, the neither the folder nor the _variables.scss exist.
However, they are available in the tmp folder.

Is it possible to include them in dist as well?

Furthermore i could also imagine to ship some other files with the lib, for example images.
Is this also possible? (i haven't tried yet with files other than scss)

Thanks a lot and best regards,
Matthias

**Comment by tinesoft** [comment]
Hi @matthiasscudlik 

Yes it is possible to include your your scss, images,... files in the final built package.
For that, just update the **"npm-package"** task in your `gulpfile.js` to include those:

```
// Prepare 'dist' folder for publication to NPM
gulp.task('npm-package', (cb) => {
  ...
  // copy the needed additional files in the 'dist' folder
  pump(
    [
      gulp.src(['README.md', 'LICENSE', 'CHANGELOG.md',
       <!-- defines the additional  files you want to include in your package here-->
      `${config.buildDir}/styles/**/*.scss`,
      `${config.buildDir}/images/**/*.(png|jpe?g)`,

      `${config.buildDir}/lib-es5/**/*.js`,
      `${config.buildDir}/lib-es5/**/*.js.map`,
      `${config.buildDir}/lib-es5/**/*.d.ts`,
      `${config.buildDir}/lib-es5/**/*.metadata.json`]),
      gulpFile('package.json', JSON.stringify(targetPkgJson, null, 2)),
      gulp.dest(config.outputDir)
    ], cb);
});

```

Let me know if it worked for you,


Cheers

**Comment by matthiasscudlik** [comment]
@tinesoft: thanks alot for the quick reply, in general it works.

I added the line `${config.buildDir}/lib/core/scss/**/*.scss`, but unfortunately the files are now copied to the root directory (i'd probably want core/scss).

I tried to add another gulp.src()
```
gulp.src([`${config.buildDir}/lib/core/scss/**/*.scss`], { base: `${config.buildDir}/core/scss` }),
```
but  then the metadata.json and typings got lost - any idea? (i'm not a gulp expert unfortunately)

Thanks a lot!

**Comment by tinesoft** [comment]
Hi,

What is the current structure of the files in your `src/` folder? 
and what structure would you like to have in the distributed library (`dist/`)

**Comment by matthiasscudlik** [comment]
Currently the structure looks like this (i think is has to be in src at least):

![ng-tools-ux_-_visual_studio_code_2018-01-07_11-51-02](https://user-images.githubusercontent.com/545229/34648782-42029d4a-f3a1-11e7-89fe-9b1c796385c6.png)

.. and for the beginning i think i'd just want to copy it "as is" to `dist/core/scss/_colors.scss`. The structure might change in the future as i'm not yet 100% sure about it. I'd really appreciate it if there is a way to set the target directory individually for each filetype (i.e. if images or other files will be included). 

Thanks a lot ! :)

**Comment by tinesoft** [comment]
Hi @matthiasscudlik 

Sorry for the delay. 
The generator currently offers no way to set target directory for each filetype, and i don't think it will because this is too specific. Most libraries only need to export the `*.js`, `*.js.map`, `*.metadata.json`, and  `*.d.ts` files.
Besides, it is very easy to customize the export for other file types, as explained.

> 
> Update: i managed to archive it with a regex, which seems kind of wrong (i.e. when i have multiple core / scss folders)
> 
> `${config.buildDir}/lib/**/core/**/scss/**/*.scss`,

By the way, your regex `${config.buildDir}/lib/**/core/**/scss/**/*.scss` can be simplified as such `${config.buildDir}/lib/**/*.scss`. The `**` means you don't care in which specific subfolder(s) the `*.scss` are.

**Comment by matthiasscudlik** [comment]
I was originally using your simplified regex but i don't use it anymore for two reasons:
1. the simplified reges would expose all scss files, including the ones from my components. But i only want to expose the scss files containing variables and what i want to expose as "theme"
2. when i add /**/ in front of a folder, the folder structure will actually stay as it is

I'll close the issue, thanks a lot for your support :)
