### ISSUE TITLE
Generator not creating dist folder when using Jest, but it's working fine with karma.

### ISSUE THREAD

**Issue by BenevidesLecontes** [tinesoft/generator-ngx-library#147]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

Windows 10, macOs Sierra

### Generator Version

5.5.0

### Tools Version

Yo 2.0.0
node v8.9.3
Yarn 1.3.2, npm 5.5.1
Angular 5.2.4
### Repro steps.

Create new project, select jest as test framework and try yarn or npm start.

### Desired functionality.

Need the generator create dist folder.

**Comment by tinesoft** [comment]
Hi @BenevidesLecontes 

> 
> Repro steps.
> Create new project, select jest as test framework and try yarn or npm start.


The `dist/` is only created when you _build_ the project (`gulp build[-watch[-fast]]` tasks).
Not when you `npm|yarn start`...

**Comment by tinesoft** [comment]
Feel free to re-open with more info, if this is still an issue...
