### ISSUE TITLE
permission denied with SUDO

### ISSUE THREAD

**Issue by MurhafSousli** [tinesoft/generator-ngx-library#17]
Hi @tinesoft 👋
I want to use this project for my workflow, I am running Ubuntu 17.04 but I get this issue at the end of the generator
```
npm ERR! Linux 4.10.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "link"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! path /home/murhaf/Github/test/dist
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '/home/murhaf/Github/test/dist' -> '/usr/lib/node_modules/ngx-progressbar'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, symlink '/home/murhaf/Github/test/dist' -> '/usr/lib/node_modules/ngx-progressbar'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '/home/murhaf/Github/test/dist',
npm ERR!   dest: '/usr/lib/node_modules/ngx-progressbar' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/murhaf/Github/test/dist/npm-debug.log
[13:18:48] 'link' errored after 379 ms
[13:18:48] Error: Command `npm link` failed with exit code 243
    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
ERROR!
[gulp link] Failed to link the library...
```
In fact, I ran `sudo yo ngx-library`, Is there some internal tasks that needs sudo permissions?

**Comment by tinesoft** [comment]
Hi @MurhafSousli :wave: ,

You don't need SUDO privileges to run the command, a simple `yo ngx-library` inside your target folder should be enough.

A couple of things to checks though, does the `/home/murhaf/Github/test/dist` folder exists? Normally if the previous post-install step of the generator  succeeded (`gulp package`) then the answer should be yes.

Can you post the full output of  `yo ngx-library` (with all provided options if any) ?

**Comment by tinesoft** [comment]
Please reopen, if still facing the issue.

**Comment by MurhafSousli** [comment]
Again I get the same problem with `link`

![image](https://user-images.githubusercontent.com/8130692/27593460-eb0dbb34-5b5f-11e7-8eac-266caa48dd2f.png)

**Comment by tinesoft** [comment]
Hi Murhaf,

The issue with TsLint is being addressed and will be fixed soon (dependencies incompatibility when targeting Angular v4).

Regarding the permission issue, it looks like you're not allowed to write to `/usr/lib/node_modules/` folder (which is what `npm link` does). I think i had a similar issue on my mac, with the default `node` that was installed.  I had to remove it, and properly re-install it with `Homebrew`, which set permissions correctly.
 
You can  follow [Fixing npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) from official npm site.

**Comment by tinesoft** [comment]
did it work for you?

**Comment by MurhafSousli** [comment]
I just tried it now, I changed my npm global directory in home dir and it worked :+1:  Thanks @tinesoft
