### ISSUE TITLE
Html files not copied to output when loaded into Component with templateUrl

### ISSUE THREAD

**Issue by dbaines30** [tinesoft/generator-ngx-library#28]
I'm sure it's something related to the Rollup configuration but I'm unable to get the html files to be included in the dist output when referencing html templates via the templateUrl property in a component.

`import {Component} from '@angular/core';

@Component({
    selector: 'dashboard-page',
    templateUrl: 'dashboardPage.template.html'
})

export class DashboardPage {

}`

**Comment by tinesoft** [comment]
Hi @dbaines30 

Thank you for your input. I have actually identified that bug yesterday ( :) ).
It's due to the inlined version of your library not being referenced in the `tsconfig-aot.json` file used for building the library package .

Please changes the following properties `"rootDir"` and `"files"` as such:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "es6",
        "lib": [
            "es6",
            "dom"
        ],
        "moduleResolution": "node",
        "declaration": true,
        "experimentalDecorators": true,
        "baseUrl": ".",
        "stripInternal": true,
        "outDir": "./dist",
        "rootDir": "./dist/inlined", //generated by 'inline-templates' task in gulpfile.js 
        "sourceMap": true,
        "inlineSources": true,
        "skipLibCheck": true,
        "typeRoots": [
            "node_modules/@types"
        ]
    },
    "files": [
        "./dist/inlined/index.ts"
    ],
    "exclude": [
        "node_modules",
        "dist",
        "demo",
        "config",
        "coverage",
        "src/**/*.spec.ts"
    ],
    "angularCompilerOptions": {
        "strictMetadataEmit": true,
        "skipTemplateCodegen": true
    }
}

```

Let me know if that  works for you,  i will release a hot fix tonight.

**Comment by dbaines30** [comment]
Perfect, works like a dream now. Thanks for the fast turnaround.
