### ISSUE TITLE
Module not found: Error: Can't resolve '<DEPENDENCY_NAME>'

### ISSUE THREAD

**Issue by bohoffi** [tinesoft/generator-ngx-library#3]
I've got an external dependency imported as:
```
import * as Vex from 'vexflow';
```
When I try to serve the demo application I get the following error:
```
ERROR in ../dist/inlined/common/model/common/chord.ts
Module not found: Error: Can't resolve 'vexflow' in 'C:\WebStorms\ngx-score\dist\inlined\common\model\common'
 @ ../dist/inlined/common/model/common/chord.ts 4:0-31
```

Did I miss some steps to provide the dependency to the <dist>-sources?

**Comment by tinesoft** [comment]
Hi @bohoffi ,

Thanks for using the library.

I need more details to help you. better, but here are a couple of thing you can try?
 
* did you add `vexflow` as `dependencies` of both your library and demo's `package.json`?
* did you add typings for vexflow `npm install -D @types/vexflow` in library and demo  root folder ? This may not be required, but i strongly recommend it for better development experience.
* `vexflow` seems to be  needed in the [HTML script Tag section](https://github.com/angular/angular-cli/wiki/stories-global-scripts) of your main `index.html`, did you add it to `demo/.angular-cli.json`'s `"scripts"` section ? (see [global scripts on Angular-CLI](https://github.com/angular/angular-cli/wiki/stories-global-scripts))
```
"scripts": [
        "../node_modules/vexflow/releases/vexflow-min.js"
      ],
```

Try these, and let me know if still failing


Cheers

**Comment by bohoffi** [comment]
Ok, installing `vexflow` as a dependency of the demo project solved the issue.

Thank you for your quick reply ;)
