### ISSUE TITLE
Failed to package the library on node >=8...

### ISSUE THREAD

**Issue by MurhafSousli** [tinesoft/generator-ngx-library#52]
Hi Tine,
I generated a library using `yo ngx-library` and I got this error `ERROR!
[gulp package] Failed to package the library...`

![image](https://user-images.githubusercontent.com/8130692/28341442-67183d36-6c1c-11e7-915f-f43147b2e5da.png)

Last time after I fixed my npm permission and it was working, I don't know why It didn't work this time!
Cheers.

**Comment by tinesoft** [comment]
Hi @MurhafSousli ,

I never encountered that error before...
But anyway, i can see from the logs that  you're using an old version of the generator.
I  strongly recommend you to upgrade to latest [v3.0.0](https://github.com/tinesoft/generator-ngx-library/releases/tag/v3.0.0), released 2 days ago.

`npm install -g generator-ngx-library`
or
`yarn global add generator-ngx-library`

A lot of improvements have been made on the generator!

Try that and let me know

**Comment by pratikthecook** [comment]
i get the same error on node 8.1.4 & npm 5.3.0 with ur current 3.0.0

**Comment by tinesoft** [comment]
Hi @pratikthecook ,

Can you post your logs or confirm that the following line is displayed in console:

> Almost done (2/3). Running gulp **_npm-package_** to prepare your library package in dist/...

and not

> Almost done (2/3). Running gulp **_package_** to prepare your library package in dist/...

Also, can you provide 
- OS Name & Version?
- Targeted Angular version (2.x.x or 4.x.x) ?

Thanks

**Comment by tinesoft** [comment]
Also, in case you have upgraded  your existing library (generated with an old version of the generator),
make sure **you didn't skip changes on the `gulpfile.js`** when prompted to during conflict resolution...

**Comment by pratikthecook** [comment]
No,im creating a new one
Check the screens, im guessing require-dir is causing the issue, as somehow the package generator is downloading an older version rather than 0.3.2.
![ngx-1](https://user-images.githubusercontent.com/16317113/28416500-ea8e37aa-6d71-11e7-929a-62faca558867.png)
![ngx-2](https://user-images.githubusercontent.com/16317113/28416508-ef85898e-6d71-11e7-8363-2d44dbdc28ae.png)

I completed the 2/3 step by running sudo gulp npm-package after manualy replacing the require-dir latest version, whats the last step?

**Comment by tinesoft** [comment]
`require-dir` is not a direct `devDependencies` of the generator.

This seems to be an issue with your version of `Yarn`. Could you please update it to latest and re-run the generator?

The last step of the installation is `gulp link` (required only once, to symlink to the locally build lib in `dist/`)

**Comment by pratikthecook** [comment]
im trying the whole process of reinstalling npm/node/yarn , will update

**Comment by pratikthecook** [comment]
installed yarn 0.27.5 issue still persists :(

**Comment by tinesoft** [comment]
I have just found this: aseemk/requireDir/issues/45 :  which confirm there was indeed an issue on **Node v8.x.x** with that package (used internally by `gulp-git`, whose the generator depends upon) . The issue was fixed in 0.3.2.

Could you clean your Yarn cache and re-rerun the generator?
`yarn cache clean`

**Comment by tinesoft** [comment]
I have upgraded `gulp-git` to latest version and tested against `node 8`, everything [works great now](https://travis-ci.org/tinesoft/generator-ngx-library/builds/255684983).
I will released 3.0.1 once home.

Thank you both for reporting the issue!

Cheers

**Comment by pratikthecook** [comment]
Welcome @tinesoft. Issue resolved

**Comment by tinesoft** [comment]
Just released [v.3.0.1](https://github.com/tinesoft/generator-ngx-library/releases/tag/v3.0.1) 🎉 ! 

Happy ng-hacking!

**Comment by MurhafSousli** [comment]
Hey, I updated and cleared the cache for yarn, I am still getting the same error!

**yo@2.0.0**
**generator-ngx-library@3.0.1**

**Comment by tinesoft** [comment]
Hi @MurhafSousli ,

Something is wrong here... if you upgraded `generator-ngx-library` to `v3.0.1,` and re-ran it,
then the `gulp-git` version should be **2.4.1** not **1.12.0**....

If you did re-run on an existing project, make sure you **didn't skip changes** on the `gulpfile.js` nor `package.json` when prompted to during conflict resolution...

**Comment by MurhafSousli** [comment]
@tinesoft, I didn't re-run on existing project, every time I test it on a new empty folder
![image](https://user-images.githubusercontent.com/8130692/28492135-d66bfb14-6f05-11e7-8be3-2c95b61770e8.png)

**Comment by MurhafSousli** [comment]
@tinesoft I finally got it to work on my machine, This is the best library starter thank!

**Comment by tinesoft** [comment]
Glad to know friend ;)
Enjoy!
