### ISSUE TITLE
Can't create project

### ISSUE THREAD

**Issue by erperejildo** [tinesoft/generator-ngx-library#76]
I install everything with no errors and I get this error when I try to create the project:
<img width="704" alt="screen shot 2017-09-06 at 10 58 34" src="https://user-images.githubusercontent.com/5629919/30106153-7e974aae-92f2-11e7-9948-d4a825f963c5.png">
I'm using Mac. I'll try later on today with Windows

**Comment by tinesoft** [comment]
Hi @erperejildo ,

Thanks for your using the generator.
For your future issues, please provide the minimum info requested in the issue template,
this helps understanding and reproducing the issue, and so providing fastest answer.

I just tried the  lastest version of  the generator(`3.2.0), on mac os el captain, and it works fine.

try
```
npm uninstall -g generator-ngx-library
npm install -g generator-ngx-library
```
or 
yarn global remove generator-ngx-library

**Comment by erperejildo** [comment]
same error...

What else do you need?
I'm using latest os, Node and this lib version.

**Comment by tinesoft** [comment]
Are you using `npm` or `yarn`? which version? Which version of `yo` are you using? 

This may have a influence on the issue you are having, and is the reason why these kind of  information are present in the issue template.

**Comment by erperejildo** [comment]
npm 3.10.3
yo 2.0.0

**Comment by tinesoft** [comment]
Ok, 

I'm testing with both yarn (0.27.5) and npm (5.x.x),
Never had issue with npm 3.x.x before.

Did you try uninstalling and reinstalling the generator?

**Comment by erperejildo** [comment]
Yes.

I'll try updating npm and if doesn't work I'll update Node

**Comment by tinesoft** [comment]
Roger!

Let me know if issue still persist after that

**Comment by erperejildo** [comment]
Updated both and same error:
npm 8.4.0
node 5.3.0

Is there anything else I can check?

**Comment by tinesoft** [comment]
Looking more closely to the error, it seems your node environment is somehow still pointing to old `node v4.x.x`, which doesn't understand ES6 syntax (in particular the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)) used by the generator. 

Did you update node through homebrew? or via the [binary on their website](https://nodejs.org/en/)?

You can try [nvm](https://github.com/creationix/nvm), to easily manage node versions.

**Comment by tinesoft** [comment]
Are you still having the issue?

**Comment by erperejildo** [comment]
Still having the issue on Mac but it's working on Windows, which is enough for me
