### ISSUE TITLE
Build failed creating a demo project project

### ISSUE THREAD

**Issue by jbphillips** [tinesoft/generator-ngx-library#89]
### OS and Version?
 Windows 7

### Generator Version
4.1.0

### Tools Version
Output from: `yo --version`, 2.0.0
Output from: `node --version`, 6.11.3
Output from: `npm -v` 5.3.0

### Targeted Angular version
2+

### Repro steps.
Install Yeoman: npm install -g yo
Install Gulp: npm install -g gulp-cli
Install Angular CLI: npm install -g @angular/cli
Install -g generator-ngx-library

Once installed, simply run the following command:
$ yo ngx-library

### The log given by the failure.
Project creation fails right away with following in the terminal window:
TestLibrary>yo ngx-library
C:\Users\jphillips\AppData\Roaming\npm\node_modules\generator-ngx-library\node_modules\chalk\index.js:8
const isSimpleWindowsTerm = process.platform === 'win32' && !process.env.TERM.toLowerCase().startsWith('xterm');
                                                                             ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.<anonymous> (C:\Users\jphillips\AppData\Roaming\npm\node_modules\generator-ngx-library\node_modules\cha
lk\index.js:8:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jphillips\AppData\Roaming\npm\node_modules\generator-ngx-library\app\index.js:5:1
5)
    at Module._compile (module.js:570:32)

### Desired functionality.
An initial demo project

**Comment by sajankumar** [comment]
Same issue facing in Windows 10 
![issue](https://user-images.githubusercontent.com/5716889/31025690-1f66a4c2-a561-11e7-9757-6578cdad3331.PNG)

**Comment by tinesoft** [comment]
Hi guys!

Thanks for reporting this.
The issue seems to only occur on Windows 10 and may be related to https://github.com/chalk/chalk/issues/164, (`chalk` is  is a core dependency of the generator).

It has been fixed in latest version of chalk (starting `v2.0.1`).

I have updated the generator's deps, and released 🎉 [v4.1.1](https://github.com/tinesoft/generator-ngx-library/releases/tag/v4.1.0) that should fix the generation issue.

Please confirm and fill free to re-open if not (don't have windows 10, so cannot test myself).

Cheers!

**Comment by jbphillips** [comment]
Thank you!

It was reported also an issue with windows 7. Your 4.1.1 works for me now,
thank you!

Cheers!

**Comment by sajankumar** [comment]
Thank you!

It works for me now on Windows 10.
