### ISSUE TITLE
How to use environment.ts from demo application into main distributed component

### ISSUE THREAD

**Issue by vikrantsahoo** [tinesoft/generator-ngx-library#97]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### OS and Version? 

> **Windows 7**

### Generator Version 

**3.3.0**

### Tools Version

Output from: `yo --version`, **2.0.0**
Output from: `node --version`,  **6.11.2**
Output from: `npm -v` or `yarn --version` **3.10.10**

### Targeted Angular version
 4.3.1

### Repro steps.

1. I created my distributed component using yo ngx-library
and also included demo app.
2. Under demo I have environment.ts file which I want to use in main src folder not in demo app
3. How I can use any resources from demo app to distributed component src
4. I don't want to include environment.ts in main component file I want it to be in demo OR in my main app but how distributed component can use any resource from demo or any app.

**Comment by tinesoft** [comment]
Hi @vikrantsahoo ,

I don't really understand what  you are trying to achieve here... Please explain better.

`environment.ts` is only used by the demo app, and is managed by angular-cli, to define
 properties that you can use in the demo app, and whose values may vary based on targetted environment (dev, prod, etc), it is not meant to be used by your library in `<root folder>/src` folder, and you shouldn't need to anyway.

What resources from demo app, do you want to use in library too?

**Comment by tinesoft** [comment]
closing for now, as no feedback was provided in over 3 weeks...
